### ISSUE TITLE
Unparseable date Exception

### ISSUE THREAD

**Issue by mpaatz** [IOT-DSA/sdk-dslink-java#44]
Hi,

I imported some Weather nodes and tried to use the long timestamp of the values when I got the following exception:

`Exception in thread "Thread-32" java.lang.RuntimeException: java.text.ParseException: Unparseable date: "2016-08-10T12:51:57.916426+0000"
    at org.dsa.iot.dslink.util.TimeUtils.parseTz(TimeUtils.java:80)
    at org.dsa.iot.dslink.node.value.Value.getTime(Value.java:316)
Caused by: java.text.ParseException: Unparseable date: "2016-08-10T12:51:57.916426+0000"
    at java.text.DateFormat.parse(DateFormat.java:366)
    at org.dsa.iot.dslink.util.TimeUtils.parseTz(TimeUtils.java:78)`

Thanks

**Comment by a-hansen** [comment]
Fixed
