### ISSUE TITLE
unable to use slf4j binding of my choice

### ISSUE THREAD

**Issue by santhosh-tekuri** [IOT-DSA/sdk-dslink-java#7]
I would like to use slf4j jdk14 binding for my application.
so i added it to my dependencies:

```xml
<dependencies>
    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-jdk14</artifactId>
        <version>1.7.12</version>
    </dependency>
    <dependency>
        <groupId>org.iot-dsa</groupId>
        <artifactId>dslink</artifactId>
        <version>0.13.0-SNAPSHOT</version>
    </dependency>
</dependencies>
```
on running my application, I got following exception:

```
Exception in thread "main" java.lang.ClassCastException: org.slf4j.impl.JDK14LoggerFactory cannot be cast to org.slf4j.impl.LoggerFactoryImpl
	at org.dsa.iot.dslink.util.log.LoggingBridge.getLoggerFactory(LoggingBridge.java:55)
	at org.dsa.iot.dslink.util.log.LoggingBridge.setLevel(LoggingBridge.java:24)
	at org.dsa.iot.dslink.util.log.LogManager.setLevel(LogManager.java:73)
	at org.dsa.iot.dslink.DSLinkFactory.generate(DSLinkFactory.java:46)
	at test.SimpleTest.main(SimpleTest.java:36)
```

**Comment by samrg472** [comment]
You need to provide your own LogBridge instance otherwise the default is used, which expects the standard logging module that I provide.
